### ISSUE TITLE
关于预测目标问题

### ISSUE THREAD

**Issue by packer-c** [xlwang233/STSeq2Seq#2]
你好！感谢作者的文章和分享代码。

请问一下文章中的分别预测15min, 30min, 60min指的是预测未来15, 30, 60分钟内所有的交通流值，还是指的预测未来15,30,60时刻的某一个值？

**Comment by xlwang233** [comment]
Hi @packer-c ,

Thanks for your question. The goal is to predict the future 1 hour traffic states. You can think of the output as a vector containing 12 elements, with each one being the traffic value for each of the 5 minutes interval. But we only select the 15, 30, and 60 (i.e., 3, 6, and 12 steps ahead) for evaluation of the performance. Regarding your question, the output is the value at exactly each of those time interval rather than the average/sum of all the values. I hope this answers your question. Cheers.

**Comment by packer-c** [comment]
Hi! @xlwang233 
Thank you for your kind reply.
Taking an example, we want to predict 1 hour, so the input is 12 historical timestamps, and the output is 12 future timestamps (12 steps ahead)? Right?

**Comment by xlwang233** [comment]
> Hi! @xlwang233 Thank you for your kind reply. Taking an example, we want to predict 1 hour, so the input is 12 historical timestamps, and the output is 12 future timestamps (12 steps ahead)? Right?

Yes exactly.
